### ISSUE TITLE
Compile error: overloaded function with no contextual type information

### ISSUE THREAD

**Issue by LukasvdWiel** [Manuel1605/ImpalaJIT#3]
Dear Manuel,

I needed ImpalaJIT to compile SeisSol. Compiling Impala with GCC 10.2 returned a few errors, indicating missing type information:

In file included from /trinity/opt/apps/software/ImpalaJIT/9maart2022/ImpalaJIT/compiler/code-gen/code_generator.cc:26:
/trinity/opt/apps/software/ImpalaJIT/9maart2022/ImpalaJIT/compiler/code-gen/include/ptr_map_container.hh: In static member function ‘static void FunctionPtrMap::initialize_map()’:
/trinity/opt/apps/software/ImpalaJIT/9maart2022/ImpalaJIT/compiler/code-gen/include/ptr_map_container.hh:41:64: error: overloaded function with no contextual type information
   41 |             map["pow"] = reinterpret_cast<externalFunction>(pow);
      |                                                                ^
/trinity/opt/apps/software/ImpalaJIT/9maart2022/ImpalaJIT/compiler/code-gen/include/ptr_map_container.hh:42:66: error: overloaded function with no contextual type information
   42 |             map["sqrt"] = reinterpret_cast<externalFunction>(sqrt);
      |                                                                  ^
/trinity/opt/apps/software/ImpalaJIT/9maart2022/ImpalaJIT/compiler/code-gen/include/ptr_map_container.hh:45:65: error: overloaded function with no contextual type information
   45 |             map["abs"] = reinterpret_cast<externalFunction>(fabs);
      | 

Best wishes, and hopefully this is not too difficult to fix,
Lukas

**Comment by manuel-fasching** [comment]
Hi, thanks for reaching out. 

I fixed this issue by including `cmath` instead of `math.h`. Can you verify that the build works for you?

Best,
Manuel

**Comment by LukasvdWiel** [comment]
Dear Manuel,

thank you for the surprisingly fast reply, and correct fix! 
Verified that is compiles correctly.

Cheers
Lukas
